### PR TITLE
Update target of link to Office Add-ins docs

### PR DESCRIPTION
**Pull request by kbrandl**

### CODE REVIEW

**Comment by kbrandl** [comment]
@Linda-Editor can you please merge this PR when you have a chance? Thank you!

**Comment by Linda-Editor** [comment]
@kbrandl Hi Kim, I'm actually not at Microsoft anymore (budget ran out); however, I can still merge this for you. Linda Lu is handling everything going forward.  @lindalu-MSFT - can you merge this to live? Thanks...

**Comment by kbrandl** [comment]
@Linda-Editor thank you! Hope you're able to re-join us at some point in the future!

**Comment by Linda-Editor** [comment]
@kbrandl Thanks, Kim. I hope so too!

**Comment by lindalu-MSFT** [comment]
@Linda-Editor Thanks for the merge! 👍

**Pull request merged**
